# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExceptpurchaseprocess():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_exceptpurchaseprocess(self):
    self.driver.get("https://store.anypass.jp/resale-list")
    self.driver.set_window_size(1024, 564)
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted > .button__element").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted > .button__element").click()
    self.driver.find_element(By.CSS_SELECTOR, ".resale__wrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-select:nth-child(1) > .select-selected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-select:nth-child(1) div:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-select:nth-child(1) > .select-selected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-select:nth-child(1) > .select-items > div:nth-child(2)").click()
  
