# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAnypasslogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_anypasslogin(self):
    self.driver.get("https://www.google.com/search?q=anypass+store&rlz=1C5CHFA_enJP948JP949&oq=a&gs_lcrp=EgZjaHJvbWUqDggAEEUYJxg7GIAEGIoFMg4IABBFGCcYOxiABBiKBTIGCAEQRRhAMgYIAhBFGDwyBggDEEUYPDIGCAQQRRg8MgYIBRBFGDwyBggGEAUYQDIGCAcQBRhA0gEIMTI4OWowajSoAgCwAgA&sourceid=chrome&ie=UTF-8")
    self.driver.set_window_size(1024, 640)
    element = self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pc:nth-child(2)").click()
    self.driver.find_element(By.NAME, "mail").send_keys("33shunshun33@gmail.com")
    element = self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .notranslate .VuuXrf")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".checkmark").click()
    self.driver.find_element(By.NAME, "password").send_keys("Banjapoxanypass!")
    self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted:nth-child(4) > .button__element").click()
  
