# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import os
from datetime import datetime




def beep(freq, dur=100):
    import os
    os.system('play -n synth %s sin %s' % (dur/1000, freq))

class TestAnypass():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    #options.add_argument('--headless')  # ヘッドレスモードを有効にする
    self.driver = webdriver.Chrome(options=options)
    options.add_experimental_option("detach", True)
    self.vars = {}
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_anypass(self):
    self.driver.get("https://store.anypass.jp/resale-list?sort=0")
    n=0
    flag=1
    while True:          
      print(n)
      try:
        select_element = WebDriverWait(self.driver, 30).until(
          EC.element_to_be_clickable((By.CSS_SELECTOR, ".custom-select:nth-child(1) > .select-selected"))
        )
        if flag==1:
          self.driver.find_element(By.CSS_SELECTOR, ".container").click()
          flag=0
          self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted > .button__element").click()
        else:
          select_element.click()
          self.driver.find_element(By.CSS_SELECTOR, ".custom-select:nth-child(1) div:nth-child(1)").click()
      except NoSuchElementException:
        print("most recent button")
      except TimeoutException:
        print("TimeoutException")  
        
      #self.driver.find_element(By.CSS_SELECTOR, ".checkmark").click()
      #self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted > .button__element").click()
    
      try:
        self.driver.find_element(By.CSS_SELECTOR, "main > div.resale__wrapper > div.details__container.resale_list > div > div > a:nth-child(1) > div > .red")
      except NoSuchElementException: 
        print("red not found")
        try:
          title_element = self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) > .item__details > .title")
          if "TAYLOR SWIFT | THE ERAS TOUR" in title_element.text:
            break
        except NoSuchElementException:
          print("title not found")
      
      n+=1
      login = 1
      if(n%10==1):
        try:    
          pc_element = self.driver.find_element(By.CSS_SELECTOR, ".menu-one-side > .pc")
          if pc_element.text.strip() == 'Login / Registration':
            flag=1
            login = 0
          if login==0:
            try:
              self.driver.find_element(By.CSS_SELECTOR, ".pc:nth-child(2)").click()
              self.driver.find_element(By.NAME, "mail").send_keys("33shunshun33@gmail.com")
              self.driver.find_element(By.NAME, "password").send_keys("Banjapoxanypass!")
              self.driver.find_element(By.CSS_SELECTOR, ".button__container__inverted:nth-child(4) > .button__element").click()
            except NoSuchElementException:
              print("error while trying login")
        except NoSuchElementException:
          print("pc not found")      
          

        
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) > .item__details").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkmark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".buy__container > div").click()
    current_time = datetime.now()
    formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
    print("date and time:", formatted_time)
    beep(500, 5000)
    input()
