# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestAnypass():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    #options.add_argument('--headless')  # ヘッドレスモードを有効にする
    self.driver = webdriver.Chrome(options=options)
    options.add_experimental_option("detach", True)
    self.vars = {}
    
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_anypass(self):
    self.driver.get("https://store.anypass.jp/resale-list?sort=0")
    n=0
    while True:
      try:
        title_element = self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) > .item__details .title")
        if "TAYLOR SWIFT | THE ERAS TOUR" in title_element.text:
          break  
      except NoSuchElementException:
          # 要素が見つからない場合、またはStaleElementReferenceExceptionが発生した場合、例外が発生する可能性があるため捕捉して処理
        print("Element not found or stale, retrying...")
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) > .item__details").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkmark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".buy__container > div").click()
    input()
      
  
